version: '3'

services:
   registry:
      image: registry
      ports:
         - "5000:5000"
      restart: always
      volumes:
         - ./data/registry:/var/lib/registry
         - /etc/localtime:/etc/localtime
      networks:
         - my-net
networks:
   my-net: