version: '3'

services:
   gitlab:
      image: gitlab/gitlab-ce:latest
      ports:
         - "412:443"
         - "812:80"
         - "100:22"
      restart: always
      volumes:
         - ./config:/etc/gitlab
         - ./logs:/var/log/gitlab
         - ./data:/var/opt/gitlab
         - /etc/localtime:/etc/localtime
      networks:
         - my-net
networks:
   my-net: