version: '3'

services:

   nginx:
      image: nginx:1.13 #镜像名称和版本
      ports:
         - "810:80"
      restart: always
      volumes:
         - ./web/public:/usr/share/nginx/html
         - ./nginx/logs:/var/log/nginx
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
         - ./nginx/conf.d:/etc/nginx/conf.d
         - /etc/localtime:/etc/localtime
      networks:
         - my-net

   php:
      image: 172.16.32.59:5000/php7.13-fpm:latest
      ports:
         - "9010:9000"
      restart: always
      volumes:
          - ./web:/var/www/html
          - ./php/etc/php-fpm.conf:/usr/local/etc/php/php-fpm.conf:ro
          - ./php/etc/php.ini:/usr/local/etc/php/php.ini:ro
          - ./php/logs:/var/phplogs
          - /etc/localtime:/etc/localtime
      networks:
         - my-net

networks:
   my-net:
     external:
       name: my-net
